version: '3.5'
services:
  haproxy:
    build: .
    image: nickadam/haproxy-dev:1.0
    environment:
      - DEV_COMMON_NAME=myservice.example.com
      - DEV_ALT_NAMES=*.example.com,*.example.net,*.inst.example.com,example.com,example.net,127.0.0.1
      - DEV_DEFAULT_BACKEND=devhost.example.com:9001
      - DEV_SERVICE_ACLS=path_beg /api,path_beg /static,path_beg /old,path_beg /whatever
      - DEV_SERVICE_BACKENDS=devhost.example.com:9000,devhost2.example.com:80,devhost3.example.com:80,devhost4.example.com:80
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - keys:/keys
volumes:
  keys: {}
